### ISSUE TITLE
Script names proposal

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-study-template#10]
This is the naming that @SophieHerbst proposes for the moment. This is open to discussion once we have an updated flowchart.
This issue is just to keep track of them
- [x] `01-import_and_filter.py`
- [x] `02-apply_maxwell_filter.py`
- [x] `03-extract_events.py`
- [x] `04-make_epochs.py`
- [x] `05a-run_ica.py`
- [x] `05b-compute_and_apply_ssp.py`
- [ ] `06a-reject_ica_components.py`
- [x] `07-make_evoked.py`
- [x] `08-group_average_sensors.py`
- [x] `09-sliding_estimator.py`
- [x] `10-time_frequency.py`

- [ ] `11-anatomy.py`
- [ ] `12-make_cov.py`
- [ ] `13a-make_forward.py`
- [ ] `14a-make_inverse.py`
- [ ] `15a-group_average_source.py`

- [ ] `13b-lcmv_beamformer.py`
- [ ] `14b-group_average_lcmv.py`

- [ ] `99-make_reports.py`

**Comment by massich** [comment]
are we still renaming the scripts based on this issue?

**Comment by agramfort** [comment]
Sure

**Comment by jasmainak** [comment]
close issue?

**Comment by massich** [comment]
@sappelhoff I would wait for @SophieHerbst
