### ISSUE TITLE
Handling of bad channels in experiments with multiple runs and sessions

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#104]
This is somewhat related to #97, but probably more urgent.

Say we have an experimental session that consists of multiple runs (or blocks). Currently, we apply  bad channel detection and SSS on each block individually. This can lead to situations where a given sensor is marked as bad in one run, but not in another; and after applying the Maxwell filter, we will be unable to tell :) I'm not sure if that's good practice? What I would have done intuitively is: scan all runs for bad channels, note those down, form the union of all bad channels and mark them as bad in ALL runs before proceeding with any interpolation / SSS. What's your stance on this?

This question could even be expanded beyond runs, to sessions. But here I feel more comfortable to treat sessions differentially.

**Comment by jasmainak** [comment]
The data anyway has rank ~70 so marking a few extra bad channels through union is not going to change much. That's my naive understanding :)

**Comment by hoechenberger** [comment]
> The data anyway has rank ~70 so marking a few extra bad channels through union is not going to change much. That's my naive understanding :)

And now assume I have a 32-channels EEG, … :)

**Comment by jasmainak** [comment]
use EEGLAB? they have more citations anyway :) :)

**Comment by hoechenberger** [comment]
And I thought _I_ was the cynical person around here 😂

**Comment by SophieHerbst** [comment]
You don't maxfilter EEG. 
What does mne.concatenate_raws do if there are different channels marked as bad in the runs to be concatenated?

**Comment by hoechenberger** [comment]
> You don't maxfilter EEG.

Hehe yes. But I could interpolate bad channels and essentially end up with something similar to Maxfiltered MEG data.

> What does mne.concatenate_raws do if there are different channels marked as bad in the runs to be concatenated?

I guess it would take the union…
Thing is, if I "fix" the channels before concatenation, they are not "bad" anymore.

**Comment by SophieHerbst** [comment]
So the problem you see is with the rank then? 
In an earlier version, we had used mne.compute_rank to get it from the data. Would that be an option? 
At the time, we decided to allow bads per run with the goal to preserve as much data as possible (for example if considerable number of sensors turns bad in the last run), but this might be too much of a special case.

**Comment by hoechenberger** [comment]
> So the problem you see is with the rank then?

No I'm not sure, I don't have any _specific_ concerns I guess, I'm just wondering what's the best approach :)

> At the time, we decided to allow bads per run with the goal to preserve as much data as possible (for example if considerable number of sensors turns bad in the last run), but this might be too much of a special case.

Good point, esp. with EEG you tend to lose sensors as the measurement progresses. Would be a waste to throw those out in the earlier runs too…

**Comment by agramfort** [comment]
I think MEG people would run max filter on each run setting bad channels for each run and let maxfilter do the rest.

maybe @SherazKhan has an opinion?

**Comment by hoechenberger** [comment]
> I think MEG people would run max filter on each run setting bad channels for each run and let maxfilter do the rest.

In this case, how would the empty-room data be treated? Use the union of bad channels of all runs, and "let maxfilter do the rest", as you call it? :)

**Comment by agramfort** [comment]
ping ping @SherazKhan :)

or maybe @larsoner has an opinion?

**Comment by hoechenberger** [comment]
> > I think MEG people would run max filter on each run setting bad channels for each run and let maxfilter do the rest.
> 
> In this case, how would the empty-room data be treated? Because there's only one per session, not per run. Would one mark the union of bad channels of all experimental runs as bad in the empty-room dataset, and "let maxfilter do the rest", as you call it? :)

Discussion with @SophieHerbst showed that, at least in her lab, they will mark the same channels as bad in the empty-room recording as were found to be bad in the experimental run that was temporally closest to the empty-room measurement.
