### ISSUE TITLE
Test datasets' empty-room recordings not stored in BIDS-compatible way?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#121]
So I'm working on emptyroom processing, and I wanted to test my code with `ds000246` and `ds000248`. Turns out that `mne-bids`' `get_matched_empty_room()` cannot discover the empty-room recordings because they're stored without the `ses` entity in their path:

https://github.com/OpenNeuroDatasets/ds000246/tree/master/sub-emptyroom/meg
https://github.com/OpenNeuroDatasets/ds000248/tree/master/sub-emptyroom/meg

Before opening an issue upstream, I wanted to ask whether this is BIDS-compliant? If it is, `mne-bids` needs to be adjusted. If it's not – idk, we'd have to switch to other datasets for testing? Or get those datasets fixed?

The BIDS validator doesn't complain, btw.

cc @sappelhoff

**Comment by agramfort** [comment]
I don't see why you would need ses for empty room as it's one run in the
morning. ses should
be optional and it has no reason to match the ses from subjects the same day

>

**Comment by hoechenberger** [comment]
Well I thought `ses` must be the recording data. That's what MNE-BIDS is expecting, at least… It's required to figure out which empty-room recording is closest to the measurement you're processing.

**Comment by hoechenberger** [comment]
Okay according to the standard it SHOULD be that way:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#empty-room-meg-recordings

> Empty-room MEG recordings capture the environment and system noise. Their collection is RECOMMENDED, before/during/after each session. This data is stored inside a subject folder named sub-emptyroom. The session label SHOULD be that of the date of the empty-room recording (e.g. ses-YYYYMMDD). The scans.tsv file containing the date/time of the acquisition SHOULD also be included. Hence, users will be able to retrieve the empty-room recording that best matches a particular session with a participant, based on date/time of recording.

**Comment by agramfort** [comment]
ok :)

then you need to fix upstream data

**Comment by hoechenberger** [comment]
The issue is that there's a SHOULD and not a MUST, so I'm afraid we'd have to do something in mne-bids… either raise an exception or bite the bullet and walk through all emptyroom files, extract the measurement data, and pick the file that matches best. Which is going to take LONG for some studies

**Comment by agramfort** [comment]
ok then let's do this

**Comment by sappelhoff** [comment]
> The issue is that there's a SHOULD and not a MUST

yeah, I'd like to have a couple of more MUSTS as well, but then we'd maybe not get so many users :man_shrugging:

**Comment by hoechenberger** [comment]
@sappelhoff What do you think of the idea of walking through `sub-emptyroom` and checking `raw.info['meas_data']` of every file?

**Comment by hoechenberger** [comment]
Well I say, if you don't store your data in an easily parsable format, you'll have to accept that parsing takes longer ;) So yeah… let's do that.

**Comment by hoechenberger** [comment]
This has been resolved upstream through https://github.com/mne-tools/mne-bids/pull/421
