### ISSUE TITLE
Handling datasets with multiple simultaneous recording modalities

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#127]
Currently we ask users to specify the `kind` of the recording to be analyzed; so e.g. if `config.kind='meg'`, we will look for data in the `meg/` sub-directory.

Now it occurred to me that according to BIDS, in cases where you have a simultaneous recording of several modalities **from the same recording device**, you store all of them **in the same place**. 

Concrete example: your device supports recording MEG and EEG simultaneously with the same sampling frequency –> you would consider the EEG data as kind of "auxiliary" data of the MEG measurement, and store the dataset e.g. as `sub-01/meg/sub-01_run-01_meg.fif`.

In comparison, if you record MEG and EEG simultaneously, but use a s**eparate EEG amplifier**, you would store the MEG data as  `sub-01/meg/sub-01_run-01_meg.fif` and the EEG data as  `sub-01/eeg/sub-01_run-01_eeg.fif`.

What this boils down to is that when we receive `kind='meg'`, we could still end up loading a dataset that contains EEG channels. This is e.g. the case with the `ds000248` dataset, as is demonstrated in [this table](https://github.com/mne-tools/mne-study-template/pull/126#issue-422717778) which was created based on `kind='meg'` processing, yet there are still EEG channels in the data. When during empty-room processing I wanted to mark the same channels as bad as in the respective experimental measurement, I would get an error message because the experimental data had an EEG channel in `info['bads']`, yet the empty-room recording naturally doesn't contain any EEG channels.

I therefore suggest that for now, we run sth like `raw.pick_types(kind)` in the pipeline as early as possible to avoid any downstream issues like the one I encountered above.

We also need to discuss how to deal with this kind of "multi-modal" data in general. Assume a user has an M/EEG dataset (same device, so saved in the same file in `meg/`) and wants to limit analysis to EEG, this is currently not possible by setting `config.kind`.

Would like to hear your opinion on this.

**Comment by agramfort** [comment]
you have config.ch_types that allows you to say if you want to use EEG,
grad , mag etc.

you can have kind='meg' and set ch_types = ['eeg'] to process the EEG
channels only?

>

**Comment by hoechenberger** [comment]
Oh, you are right!! Haha I had entirely forgotten about this property! So for my empty-room processing, I can simply filter the list of bad channels down to MEG chans and that's it.

**Comment by agramfort** [comment]
yes !

>
