### ISSUE TITLE
Add SSP and ICA to empty-room processing?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#133]
Currently these steps are simply omitted

**Comment by agramfort** [comment]
I not sure I would run SSPs or ICA on empty room. At least I've never see
this done.

>

**Comment by hoechenberger** [comment]
Oh ok! @jasmainak had raised the question why we're not doing this, so I thought it might be an important addition… @jasmainak could you elaborate? :)

**Comment by jasmainak** [comment]
humm ... I have seen @SherazKhan do it, so maybe he could elaborate? :)

but now that I think about it, maybe it's unnecessary indeed. If you're removing a spatial pattern related to eye-blinks that's already not present in empty-room data.

**Comment by hoechenberger** [comment]
Ok so let’s not do this
