### ISSUE TITLE
Evoked plot ordinates only contain UNIT, but no actual LABEL

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#150]
See the abscissa for comparison, which has label **and** unit:

![image](https://user-images.githubusercontent.com/2046265/86601480-abbab000-bfa1-11ea-917a-7e67959b7685.png)

Probably needs to be fixed upstream in MNE, but just leaving this here because I just stumbled upon this while browsing our build artifacts…

**Comment by agramfort** [comment]
what would you suggest?

>

**Comment by hoechenberger** [comment]
`Field strength (fT)` for magnetometers, and `d/dL Field strength (fT/cm)` for gradiometers. But I can already see how awkward this would be :(

**Comment by hoechenberger** [comment]
Maybe just `Signal (fT)` and `Signal (fT/cm)`?

**Comment by agramfort** [comment]
i find this not more informative. But I am obviously very biased...

>

**Comment by hoechenberger** [comment]
It just bites me very much as I had an engineering education and just writing the unit would be a no-go.. and this inconsistency between ordinate and abscissa is not very pleasant from aesthetic point of view ;)

--
