### ISSUE TITLE
Updating ds000248 (MNE "sample" dataset): Move fine-calibration and crosstalk files

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#182]
OpenNeuro dataset [ds000248](https://openneuro.org/datasets/ds000248) ships with fine-calibration and cross-talk files. Since we've now [standardized](https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#cross-talk-and-fine-calibration-files) naming of those files, I would like to update the dataset by moving:

from | to |
----- | --|
`/derivatives/ct_sparse_mgh.fif` | `/sub-01/meg/sub-01_acq-crosstalk_meg.fif` |
`/derivatives/sss_cal_mgh.dat` | `/sub-01/meg/sub-01_acq-calibration_meg.dat` |

@jasmainak I see you're the one who published the dataset on OpenNeuro. Do you think you could update it? Or grant me access so I could do it myself?

Thanks!

**Comment by jasmainak** [comment]
I just gave you access. It's the email address ending with .net

**Comment by hoechenberger** [comment]
> I just gave you access. It's the email address ending with .net

Thanks! I haven't received an email though… my account on OpenNeuro is linked to my GMail address richard.hoechenberger@gmail.com

btw I don't know if this happened just now or I never saw it before, but the latest revision of the dataset: https://openneuro.org/datasets/ds000248/versions/1.1.0 cannot be displayed correctly and claims to be from 1970… whoops.

**Comment by jasmainak** [comment]
oh dear, this was lost in my emails. I already sent an invite to your gmail address. Are you sure you didn't get it?

**Comment by hoechenberger** [comment]
@jasmainak Thanks! I didn't receive a notification but the dataset appears in my OpenNeuro dashboard now!

**Comment by hoechenberger** [comment]
(And I have writing permissions)

**Comment by sappelhoff** [comment]
It'd be awesome if the actual version on open neuro could be mirrored to the bids-examples repository.

It's looking like this currently: https://github.com/bids-standard/bids-examples/tree/master/ds000248

It'd not be a lot of work --> basically taking the exact openneuro dataset, and running something like: `find <path_to_ds> -type f -name '*.fif' -exec truncate -s 0 {} +` to zero out the big binary data files.

Then finally, making a PR to bids-examples with the updated set.

**Comment by agramfort** [comment]
I am working on it. I'll push an update of the dataset ASAP

>

**Comment by hoechenberger** [comment]
This has been fixed in the latest revision of the dataset.
