### ISSUE TITLE
Error: Surface outer skull is not completely inside surface outer skin

### ISSUE THREAD

**Issue by RickLicona** [mne-tools/mne-study-template#185]
Dear all,

Regarding the DS117 dataset. When I employ the **conductivity for 3 layers (EEG)**,  I got the next error (subject 006):
![imagen](https://user-images.githubusercontent.com/22995049/94989495-e39ea880-053a-11eb-8968-acae1dfa01dc.png)
![imagen](https://user-images.githubusercontent.com/22995049/94989499-e8635c80-053a-11eb-89dd-847243b98c4e.png)

However, employing the same subject, but with conductivity for 1 layer (MEG), there is not any error:

![imagen](https://user-images.githubusercontent.com/22995049/94989530-282a4400-053b-11eb-99a3-370953b1f140.png)

In the case of the subject 002, there is not problem with **conductivity for 3 layers (EEG)**:

![imagen](https://user-images.githubusercontent.com/22995049/94989598-b7375c00-053b-11eb-8c52-79b0fbdea84a.png)
![imagen](https://user-images.githubusercontent.com/22995049/94989606-bd2d3d00-053b-11eb-87e1-8ffa2ed50d56.png)

I only require to use the EEG data (**I know that the 3-layer is unreliable**). Is there any solution for the first error message? or do you suggest me only take the users such as 002?. The idea is to continue with the forward estimation and the inverse stepts.  

By the way, thanks for your proposal MNE pipeline ;).

**Comment by agramfort** [comment]
same remark as on the MNE list. Stick to subjects that work

>

**Comment by hoechenberger** [comment]
@agramfort I believe you received an email looking as if this issue has been re-posted here (at least I did), but in fact @jasmainak had just transferred it from the MNE issue tracker to the study template issue tracker. So this is actually a shortcoming on GH's side regarding how they set up these email notifications.
