### ISSUE TITLE
Add BEM to example gallery

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#235]
Currently, in two tests we (only) create BEM surfaces, which end up in the respective FreeSurfer derivatives directory; no Report can be generated based on this. Therefore, these two tests cannot be used as examples in our example gallery. We should change that.

**Comment by agramfort** [comment]
@hoechenberger I don't get it. If you have bem surfaces the report should be able to overlay them on the T1 MRI.

**Comment by hoechenberger** [comment]
The issue I meant to point out here is this:
If one **only** runs the BEM-creation step and doesn't process any other parts of the data (i.e. doesn't touch the electrophysiological data at all), `Report.parse_folder()` won't find anything and will crash. Therefore, two of our examples where we only create BEM surfaces from T1 and FLASH images, respectively, don't show up in our examples gallery. But I suspect that's okay – we still have our ds000248 example, where we create the BEM surfaces AND process MEG data. Closing this issue.
