### ISSUE TITLE
explain better some parameters setup for ICA 

### ISSUE THREAD

**Issue by virvw** [mne-tools/mne-study-template#25]
Since one has the choice to high-pass filter the data or not, there are several tricky questions:
(1) it seems that the ICA rejection works best if the high-pass filter is 1 Hz
(2) what if one does not want to high-pass the data, what are the options?

**Comment by jasmainak** [comment]
In the [original code](https://github.com/mne-tools/mne-biomag-group-demo/blob/master/scripts/processing/05-run_ica.py#L17), we explain that you need 1 Hz high-pass filter for learning the spatial filter, but then you can apply it to unfiltered data or high-passed data.

**Comment by virvw** [comment]
I think it should be made explicit that the 1 Hz yield better ICA outcomes
but raw data can be applied to non hpf data

**Comment by agramfort** [comment]
it can be explained by the fact that ICA models we use assume data and
sources are zero mean.

**Comment by virvw** [comment]
> In the [original code](https://github.com/mne-tools/mne-biomag-group-demo/blob/master/scripts/processing/05-run_ica.py#L17), we explain that you need 1 Hz high-pass filter for learning the spatial filter, but then you can apply it to unfiltered data or high-passed data.

So this should not be in the code but in the pipeline for new users

**Comment by virvw** [comment]
> it can be explained by the fact that ICA models we use assume data and sources are zero mean.

and this also for advanced users - we started the [Good Practice & Advice] in the pipeline for this purpose

**Comment by sappelhoff** [comment]
@virvw see also the thread on updating the ICA docs in MNE-Python: https://github.com/mne-tools/mne-python/pull/6596

closing this for now, feel free to re-open.
