### ISSUE TITLE
example config files

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-study-template#254]
Hi! @hoechenberger this is amazing work! Congrats!!

Do you think it could be useful to have the config files for your example data?
I know they are in the web, but maybe it could be useful to have them already here?
Something like mne-study-template/example-config-files
- config_ds000246.py
- config_ds000248.py
- etc
If you want I can help with this. 

Talk soon,

**Comment by agramfort** [comment]
it's all here
https://github.com/mne-tools/mne-study-template/tree/master/tests/configs

>
>

**Comment by guiomar** [comment]
Oh! Cool! I haven't seen it!! Super thanks!!
