### ISSUE TITLE
CI for mne study template

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-study-template#37]
With @sappelhoff we agreed today that a better workflow for MNE study template would be to set up the CIs to use datalad to fetch different datasets. Since it's relatively lightweight to get one subject with datalad, this can be used to run tests on many different datasets and work in a test driven manner. So, the workflow would be something like:

- add datalad to Circle CI in one pull request
- next pull request, add one dataset to .circle/config.yml and iterate until circle passes
- next pull request, add another dataset and iterate until circle passes

This way, you are guaranteed not to break datasets that already work. Go go go @sappelhoff !

**Comment by larsoner** [comment]
Sounds great. CircleCI can be a pain, let me know if you get stuck with something that does not make sense.

**Comment by sappelhoff** [comment]
closed by #35
