### ISSUE TITLE
Make "make report" work

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-study-template#47]
> Magic how little lines you need for a new dataset :)
> We should have one dataset that also does make source and ideally make report we could see as artifact on circle

_Originally posted by @agramfort in https://github.com/mne-tools/mne-study-template/pull/45#issuecomment-519565105_

related to #4 ... but the codebase has moved considerably

### To Do
- [x] turn mne-somato-data into git-annex dataset to be downloaded via datalad
- [x] make mne-somato-data work in study template with `make source`
- [x] make `make report` work

**Comment by jasmainak** [comment]
yes +100!

All your artifacts are belong to us :-)

**Comment by sappelhoff** [comment]
closing this, because the reports seem to work: https://app.circleci.com/pipelines/github/mne-tools/mne-study-template/447/workflows/c0077998-ffe1-4372-b59f-94d764069c8b/jobs/465/artifacts
