### ISSUE TITLE
Setup ICA's n_components

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-study-template#5]
The right way to set the n_components is this:
```py
meg_maxfilter_rank = raw.copy().pick_types(meg=True).estimate_rank()
ica = mne.preprocessing.ICA(n_components=meg_maxfilter_rank,
                            method=method,
                            random_state=42)
```

Plus there was the problem of centring the PCA. (check https://github.com/massich/epilepsy-biomag-2018)

_Originally posted by @massich in https://github.com/mne-tools/mne-study-template/pull/2_

**Comment by agramfort** [comment]
centering PCA is no problem for long data with baseline correction or high
filtering data but yes we should fix this

>

**Comment by massich** [comment]
@SophieHerbst proposed to do a highpass filtering and save the file to be used afterward for the ICA script. 

(@SophieHerbst 	I've been looking for it but I can't find it. Did you open the PR?)

**Comment by SophieHerbst** [comment]
will do a PR
@agramfort how long is  long data?

**Comment by agramfort** [comment]
more than 15 mins I would say

**Comment by hoechenberger** [comment]
I believe this is not an issue anymore, since we overhauled pretty mich all things ICA.
