### ISSUE TITLE
remove duplication of make_bids_basename

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-study-template#50]
there is a lot of duplicated code with `make_bids_basename`: https://github.com/mne-tools/mne-study-template/blob/master/05b-run_ssp.py#L58

If we want the scripts to be extensible, they should be simplified somehow

**Comment by sappelhoff** [comment]
isn't this related to https://github.com/mne-tools/mne-bids/pull/257 ?

**Comment by jasmainak** [comment]
I would say only partly. The issue here is that because of our setup, we cannot put `make_bids_basename` in the `config.py` which leads to the duplication. Perhaps it could be put in a `utils.py` ?

**Comment by sappelhoff** [comment]
Mhh okay, I see. However, adding more and more modules might also obscure the purpose of the study-template. @agramfort what do you think?

**Comment by agramfort** [comment]
using an object we could avoid the duplication of the acq, task, proc, rec, space parameter we use everywhere. 

Technically we would like to have a make_bids_basename with some custom / prefixed parameters as you would do with functools.partial

we could put in the config

```
from functools import partial
from mne_bids import make_bids_basename

make_bids_basename = partial(make_bids_basename, acq=acq, ...)
```

and then in our script use

`from config import make_bids_basename`

instead of 

`from mne_bids import make_bids_basename`

thoughts?

**Comment by sappelhoff** [comment]
> thoughts?

That would save us some lines in each script, but we'd still have to call the new partial with the params that change (subject, session, run)

Is this the gain you were hoping for @jasmainak ?

**Comment by agramfort** [comment]
I don't see how to avoid passing subject, run and session

>

**Comment by jasmainak** [comment]
yeah, I think I like @agramfort 's proposal! The only issue is that you can't "update" an argument that you've already passed in `partial` (I think?). This could eventually be achieved with mne-tools/mne-bids#257 but I'm fine trying this approach first to see how far it can take us.

**Comment by hoechenberger** [comment]
We're using `BIDSPath` now, so this shouldn't be an issue anymore.
