### ISSUE TITLE
How to deploy for multiple analyses

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#83]
In the case where one would like to run the pipeline

- on the same dataset multiple times with different settings, or
- on different datasets

it is unclear to me what's the best practice regarding `mne-study-template` deployment.

While the readme [suggests](https://github.com/mne-tools/mne-study-template/blob/082a959444b464603eb4f5ed5404bf19b872a1d5/README.md#running-on-your-own-data) (point 3) that one may define an `MNE_BIDS_STUDY_CONFIG` environment variable to use one global installation of the pipeline with different configurations, [the code](https://github.com/mne-tools/mne-study-template/blob/082a959444b464603eb4f5ed5404bf19b872a1d5/config.py#L707-L709) makes it clear that this is really just intended for running the CI tests. So – what gives? Currently I have multiple copies of `mne-study-template`, each with their own `config.py`, to analyze different projects.

This seems cumbersome, and it's also related to the question @agramfort [recently raised](https://github.com/mne-tools/mne-study-template/pull/74#issuecomment-617253746): Should the pipeline be a loose collection of scripts, or maybe an installable package?

One issue that often arises with "global" packages / installations is that one is usually pinned to just _one_ package version. However, with the advance of virtual environments this should be less of an issue these days. But even so, one could make use of the [version identifier](https://github.com/mne-tools/mne-study-template/blob/082a959444b464603eb4f5ed5404bf19b872a1d5/config.py#L16) in `config.py` to automatically retrieve the correct pipeline version from GitHub. PsychoPy has a [similar functionality](https://github.com/psychopy/psychopy/blob/2d534f7fe2282e2a041972cdebfba3379e6fa8c5/psychopy/tools/versionchooser.py#L41) where it allows users to specify the exact package version the experiment should be run with.

What are your general thoughts on this matter?

tagging @jasmainak @agramfort

**Comment by agramfort** [comment]
as discussed IRL you should add support for absolute path for config file

>

**Comment by jasmainak** [comment]
agree with @agramfort on this particular issue

regarding the possibility of giving users the ability to modify scripts, do you want to have that discussion here?
