### ISSUE TITLE
ds000248 dataset doesn't have `participants.tsv`

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#85]
While working on #84, I realized that the following datasets currently used in CI testing don't come with a `participants.tsv`, meaning reading them via the latest `mne-bids` will fail:

- `ds000248`
- <strike>`eeg_matchingpennies`</strike>

How should we go about this?

**Comment by hoechenberger** [comment]
Standard [says](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file) this file is optional, so `mne-bids` shouldn't fail on reading.

**Comment by hoechenberger** [comment]
Opened issue upstream: https://github.com/mne-tools/mne-bids/issues/399

**Comment by sappelhoff** [comment]
`eeg_matchingpennies` should have a participants.tsv https://osf.io/6mceu/

**Comment by hoechenberger** [comment]
> `eeg_matchingpennies` should have a participants.tsv https://osf.io/6mceu/

You're right, I retrieved the dataset from github and it seems git-annex / datalad are having some issues on my machine. 

So this still leaves the `ds000248` dataset :)

**Comment by hoechenberger** [comment]
Not a problem anymore thanks to https://github.com/mne-tools/mne-bids/pull/397
