### ISSUE TITLE
Allow noise covariance calculation from empty-room recordings

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#88]
Currently we only allow noise covariance estimation based on the pre-stimulus period. @SophieHerbst requested an easy way to plug in empty-room recordings here. Will need to dig into `mne-bids` to figure out what are our options here. Suggestions and ideas welcome!

**Comment by agramfort** [comment]
there is a way with mne-bids to get the empty room data matching the
recording. It's can be
a flag on config to use baseline or empty room.

see https://mne.tools/mne-bids/stable/auto_examples/convert_empty_room.html
https://mne.tools/mne-bids/stable/generated/mne_bids.get_matched_empty_room.html

>

**Comment by hoechenberger** [comment]
Nice, that’s exactly what we need.

**Comment by jasmainak** [comment]
well using Denis' methods, you should be able to select baseline or empty room based on log likelihood, no? :)

**Comment by jasmainak** [comment]
see the last plot here: https://mne.tools/stable/auto_tutorials/source-modeling/plot_compute_covariance.html?highlight=empty%20room

**Comment by agramfort** [comment]
@dengemann 's  method will nottell you what is the best between empty room
and baseline if test likelihood on baseline.
It's more dedicated to tell you what is the best estimator for each dataset.

>

**Comment by dengemann** [comment]
> well using Denis' methods, you should be able to select baseline or empty room based on log likelihood, no? :)

It's not so easy. The baseline will always be better. The method selects the best estimator within one noise model. But it does not tell you which noise model is more appropriate in the first place. That would require far more assumptions and a more complicated approach.

**Comment by jasmainak** [comment]
okay let's file this for future collaborations then :)

**Comment by hoechenberger** [comment]
What we _could_ do, though, is allow the user to select both and then run the affected parts of the analysis with either. But not sure if there's really demand for that. I mean, as I understand it, the selection of the data the noise cov should be based upon is conditional on your research question and experimental paradigm, so that's actually a decision you should've made _before_ starting to record any data…

**Comment by agramfort** [comment]
I would just to a flag that says if you want to use empty room or pre-stim

both are vaid choices with different assumptions

>

**Comment by jasmainak** [comment]
if it was resting state with no events, would it fail if the flat was set to pre-stim?

**Comment by hoechenberger** [comment]
Not sure, but IMHO we should definitely raise an exception if there are no events in the data and the user requests pre-stim cov calculation
