### ISSUE TITLE
Should 03-extract_events.py be dropped?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#91]
It seems this file is a leftover from the time before we had `Annotations` (or before `mne-bids` started storing events as `Annotations`).

For example, the docstring says:
https://github.com/mne-tools/mne-study-template/blob/280bde6e98d78c7b888e878e292d30cf867e20f2/03-extract_events.py#L6-L7

Now, we don't even have or use `config.stim_channel` anymore. And the events file created by this script is only ever mentioned again in `05a-run_ica.py`, albeit not _used_.

The produced event file is picked up by the `Report.parse_folder` call in `99-make_reports.py`, which creates an event plot; however, these events do not necessarily correspond to `config.event_id` in the sense that
- _all_ events are included here, not just the ones specified in `config.event_id`, and
- the events are  not labeled (i.e., just have an event number and not a "human-readable" name)

#### Proposal

We should remove `03-extract_events.py` altogether and instead change `99-make_reports.py` such that it reads events and event labels from annotations, and passes these values to `mne.viz.plot_events()` so we get properly labeled event plots of only the events the user deemed relevant (via `config.event_id`).

**Comment by agramfort** [comment]
yes 03-extract_events.py is not necessary anymore as it should be in
events.tsv file in bids

good catch. We should not need to look at stim channel anymore

>

**Comment by SophieHerbst** [comment]
Are the events put in the tsv-file resampled when resampling is applied to the data? 
Right now, resampling is done in script 02-frequency_filter.py, on raw data, before epoching. 
Using the template on my own data, I realized that when resampling from 1000 to 256 Hz, it goes from 380 to 378 events at this point. 
Also, the [documentation on resampling](https://mne.tools/dev/generated/mne.io.Raw.html?highlight=resample#mne.io.Raw.resample) says quite clearly to resample after epoching.

**Comment by hoechenberger** [comment]
I just figured that this script also implements trigger time shifting. Is this a feature we need to retain, or should this be done at the BIDS level already so we won't have to deal with it in the study pipeline? (I'm +1 on the latter)

**Comment by hoechenberger** [comment]
> Are the events put in the tsv-file resampled when resampling is applied to the data?
> Right now, resampling is done in script 02-frequency_filter.py, on raw data, before epoching.
> Using the template on my own data, I realized that when resampling from 1000 to 256 Hz, it goes from 380 to 378 events at this point.
> Also, the [documentation on resampling](https://mne.tools/dev/generated/mne.io.Raw.html?highlight=resample#mne.io.Raw.resample) says quite clearly to resample after epoching.

I will be looking into this, thanks for reporting @SophieHerbst

**Comment by agramfort** [comment]
yes it should be done when converting to bids not in the pipeline

>
